version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: flask run -h 0.0.0.0 -p 5000
    expose:
      - 5000
    ports:
      - "5000:5000"
    volumes:
        - ./:/code
